#ifndef SQUASH_ERRORS_H
#define SQUASH_ERRORS_H
#include "squash_types.h"

typedef enum {
    SQUASH_OK = 0,
    SQUASH_ERROR_INVALID_FILE = -1,
    SQUASH_ERROR_INVALID_MAGIC = -2,
    SQUASH_ERROR_UNSUPPORTED_VERSION = -3,
    SQUASH_ERROR_MEMORY = -4,
    SQUASH_ERROR_IO = -5,
    SQUASH_ERROR_COMPRESSION = -6,
    SQUASH_ERROR_INVALID_INODE = -7,
    SQUASH_ERROR_NOT_FOUND = -8,
    SQUASH_ERROR_INVALID_PATH = -9,
    SQUASH_ERROR_PERMISSION = -10,
    SQUASH_ERROR_NOT_DIRECTORY = -11,
    SQUASH_ERROR_NOT_FILE = -12,
    SQUASH_ERROR_COMPRESSION_NOT_SUPPORTED = -13,
    SQUASH_ERROR_DECOMPRESSION_FAILED = -14,
    SQUASH_ERROR_INVALID_ARGUMENT = -15,
    SQUASH_ERROR_INVALID_BLOCK = -16,
    SQUASH_ERROR_INVALID_INDEX = -17,
    SQUASH_ERROR_CYCLE_DETECTED = -18,
    SQUASH_ERROR_INVALID_DIRECTORY = -19,
    SQUASH_ERROR_NAME_TOO_LONG = -20
} squash_error_t;

SQUASH_API const char* squash_strerror(squash_error_t error);

#endif // SQUASH_ERRORS_H